// File: pwm_glitchless.v
// Generated by MyHDL 0.11
// Date: Fri Nov 13 14:33:01 2020


`timescale 1ns/10ps

module pwm_glitchless (
    clk_i,
    pwm_o,
    threshold
);


input clk_i;
output pwm_o;
wire pwm_o;
input [3:0] threshold;

reg [4:0] cnt;
reg [4:0] threshold_r;



always @(posedge clk_i) begin: PWM_GLITCHLESS_LOC_INSTS_CHUNK_INSTS_0
    cnt <= (cnt + 1);
    if (($signed({1'b0, cnt}) == (19 - 1))) begin
        cnt <= 0;
        threshold_r <= threshold;
    end
end



assign pwm_o = (cnt < threshold_r);

endmodule
