-- File: pwm_glitchless.vhd
-- Generated by MyHDL 0.11
-- Date: Fri Nov 13 14:33:01 2020


library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;
use std.textio.all;

use work.pck_myhdl_011.all;

entity pwm_glitchless is
    port (
        clk_i: in std_logic;
        pwm_o: out std_logic;
        threshold: in unsigned(3 downto 0)
    );
end entity pwm_glitchless;


architecture MyHDL of pwm_glitchless is



signal cnt: unsigned(4 downto 0);
signal threshold_r: unsigned(4 downto 0);

begin





pwm_o <= stdl(cnt < threshold_r);

PWM_GLITCHLESS_LOC_INSTS_CHUNK_INSTS_K: process (clk_i) is
begin
    if rising_edge(clk_i) then
        cnt <= (cnt + 1);
        if (signed(resize(cnt, 6)) = (19 - 1)) then
            cnt <= to_unsigned(0, 5);
            threshold_r <= resize(threshold, 5);
        end if;
    end if;
end process PWM_GLITCHLESS_LOC_INSTS_CHUNK_INSTS_K;

end architecture MyHDL;
